#version 430

layout(std430, binding = 0) buffer Input
{
    uint input_buf[];
};

layout(std430, binding = 1) buffer Output
{
    uint output_buf[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main(void)
{
    uint id = gl_GlobalInvocationID.x;

    // Read input value
    uint value = input_buf[id];

    // Change value
    value += value * 2;

    // Write output
    output_buf[id] = value;
}
